# Default configuration for Game-AI

# Screenshot capture configuration
capture:
  region: null  # Always using full screen capture now
  save_path: "screenshots"
  save_screenshots: true

# Window detection is disabled - using full screen
detect_window: false

# Current game to play
current_game: "vanity_fair"

# Vision model configuration
vision:
  # Ollama configuration
  ollama_model: "llava:latest"
  ollama_api: "http://localhost:11434/api/generate"
  
  # Qwen configuration
  qwen_api_key: ""  # Set this or use environment variable QWEN_API_KEY
  qwen_model: ""  # Set this or use environment variable QWEN_MODEL
  qwen_base_url: ""  # Set this or use environment variable QWEN_BASE_URL
  
  # Frame extraction configuration
  frame_extraction:
    max_frames: 10  # Maximum key frames to extract
    min_frames: 10  # Minimum frames to analyze for animation detection
    frame_interval: 0.2  # Time between frames in seconds
    animation_threshold: 0.05  # Threshold for detecting animation
    max_capture_time: 10  # Maximum time to capture animation in seconds
    diff_threshold: 0.1  # Difference threshold for key frame extraction
    max_image_size: [640, 480]  # Maximum image size for API requests

# Screenshot and change detection configuration
screenshot:
  save_path: "screenshots"  # Path to save screenshots
  save_screenshots: false  # Whether to save screenshots to disk
  
  # Change detection configuration
  change_detection:
    threshold: 0.05  # 5% difference threshold for detecting significant changes
    min_frames: 5    # Minimum frames to analyze for animation detection
    max_static_diff: 0.01  # 1% maximum difference for a screen to be considered static

# Game-specific configurations
games:
  # Civilization VI configuration
  civ6:
    name: "Civilization VI"
    window_name: "Sid Meier's Civilization VI"
    resolution: [1920, 1080]  # Target resolution for the game window
    regions:
      full_screen: [0, 0, 1920, 1080]
      minimap: [1650, 830, 270, 250]
      resources: [10, 10, 400, 40]
      turn_indicator: [950, 10, 100, 40]
      next_turn_button: [1800, 50, 100, 50]  # Region where the next turn button appears
    
    prompts:
      about_game: |
        Civilization VI is a 4X turn-based strategy game developed by Firaxis Games. In this game, the player leads a civilization from the ancient era through to the modern age, aiming to become the most powerful civilization in the world. The main objective is to achieve victory through one of several means: military conquest, technological advancement (science victory), cultural influence, religious dominance, or diplomatic success.

        Gameplay involves:
        - Exploration: Revealing the map, discovering resources, and meeting other civilizations and city-states.
        - Expansion: Founding new cities, developing them, and increasing the civilization's territory.
        - Exploitation: Harvesting resources, building improvements, and optimizing city production.
        - Extermination: Waging war, defending territories, and eliminating rival civilizations if needed.

        Key game systems include:
        - Tech & Civic Trees: Researching technologies and civics to unlock new units, buildings, and policies.
        - District System: Placing specialized districts on the map to develop cities in specific directions.
        - Government & Policy Cards: Choosing a government type and policies that provide various bonuses.
        - Great People: Recruiting historical figures that provide unique bonuses and abilities.
        - Wonders: Building world wonders that provide powerful bonuses.
        - Religion: Founding and spreading religions to gain various benefits.

        Based on this screenshot, describe what you see about the current game state, including map features, cities, units, UI elements, and strategic considerations.
        
      animation: |
        You are an expert Civilization VI analyst. Analyze this sequence of game frames showing an animation or game event.
        
        Focus on identifying:
        1. Event Type: Combat, Wonder completion, Natural disaster, City founding/growth, Technology/Civic discovery, Great Person activation, Religious conversion, Diplomatic action, or other game mechanics
        2. Game Mechanics: Specific rules or calculations being applied (combat strength, city yields, tech/civic requirements)
        3. UI Changes: Interface elements appearing/disappearing (notifications, tooltips, new buttons)
        4. Strategic Impact: How this event affects gameplay and future decision-making
        
        First, describe the sequence chronologically, noting key visual changes between frames.
        Then, explain the game mechanics being demonstrated and their significance in Civilization VI's systems.
        Finally, provide strategic advice on how to respond to this event, including both immediate actions and long-term planning considerations.
  
  # Vanity Fair configuration
  vanity_fair:
    name: "Vanity Fair: The Pursuit"
    window_name: "Vanity Fair: The Pursuit"  # Update this to the actual window title if known
    # resolution: [width, height]  # Optionally set if known
    prompts:
      about_game: |
        Describe Vanity Fair: The Pursuit (名利游戏) based on this screenshot. This is a classic board game where players compete to accumulate wealth and fame by acquiring properties, collecting rent, and making strategic financial decisions.

        Key gameplay elements include:
        - Moving around the board by rolling dice
        - Purchasing properties and upgrading them to increase rent
        - Paying rent when landing on opponents' properties
        - Drawing event cards that bring opportunities or setbacks
        - Managing cash flow to avoid bankruptcy
        - Trading and negotiating with other players

        Players win by being the last one standing after others go bankrupt, or by having the highest wealth when the game ends.

        Based on the screenshot, describe what you see about the game, its current state, and what appears to be happening.
      
      game_state: |
        Analyze this Vanity Fair: The Pursuit screenshot and return your analysis in JSON format. This is a board game where players compete to accumulate wealth and fame through property acquisition and strategic financial decisions.
        
        CRITICALLY IMPORTANT: You MUST carefully and accurately identify all buttons, UI elements, and controllable areas that can be interacted with for the next operation. Pay extremely close attention to the precise position and boundaries of these elements, as they will be used for automated mouse clicks and interactions.
        
        Your analysis must include the following components in a properly formatted JSON object:
        
        1. "ui_elements": An array of objects, each representing a clickable UI element with:
           - "name": Element name/identifier (be specific and descriptive)
           - "position": [x, y] coordinates as integers (must be EXACT center of the element)
           - "state": Current state ("enabled", "disabled", "selected")
           - "function": Brief description of what this element does
        
        2. "game_areas": Object mapping key areas of the game interface:
           - "board": [x, y, width, height] boundaries
           - "player_area": [x, y, width, height] boundaries
           - "controls": [x, y, width, height] boundaries
           - Any other important areas with precise coordinates
        
        3. "game_state": Object containing:
           - "phase": Current game phase ("early", "mid", "late")
           - "current_turn": Whose turn it is
           - "player_status": Object with position, cash, properties info
           - "board_state": Array of visible properties with their status
           - "resources": Object with available resources and values
           - "other_players": Array of opponent information objects
           - "events": Any visible cards or special situations
        
        4. "action_analysis": Object containing:
           - "simple": Boolean (true/false) indicating if this is a simple action. A simple action is one that requires no strategic discussion or decision-making — it's straightforward and usually mechanical. For example, clicking “Next”, entering the game, confirming a prompt, or moving through a tutorial step would all be considered simple actions.
           - "explanation": Brief explanation for why this is simple or complex
           - "action": If simple is true, include an object with action type and position (e.g., {"type": "click", "position": [x, y]})
           
        5. "monologue": A string containing your thoughts as an image analyzer about what you see in the game. This should be in Chinese (not more than 100 words, simplly express your idea), expressing your observations, analysis, or strategic thoughts about the current game state.Try to sound more like a real person, with emotions or subjective opinions when appropriate.
        
        IMPORTANT: Return ONLY a properly formatted JSON object with no additional text or explanation outside the JSON structure. The response should begin with '{' and end with '}' and be valid JSON that can be parsed. Include all analysis inside the JSON structure itself.
      
      animation: |
        Analyze this sequence of Vanity Fair: The Pursuit game frames showing an animation or game event.
        
        Focus on identifying:
        1. Event Type: Dice roll, property purchase, rent payment, card draw, auction, or other game mechanics
        2. Game Mechanics: Specific rules being applied (property values, rent calculations, special card effects)
        3. UI Changes: Interface elements appearing/disappearing (notifications, pop-ups, tooltips, menus)
        4. Resource Changes: Modifications to cash, property ownership, or other assets
        5. Player Movement: Changes in player token positions on the board
        6. Strategic Impact: How this event affects gameplay and future decision-making
        
        First, describe the sequence chronologically, noting key visual changes between frames.
        Then, explain the game mechanics being demonstrated and their significance in Vanity Fair's systems.
        Finally, provide strategic advice on how to respond to this event, including both immediate actions and long-term planning considerations.

# Monologue audio configuration using Kokoro TTS
audio:
  # TTS model repository
  tts_model: "hexgrad/Kokoro-82M-v1.1-zh"
  # Voice to use (zf_001 = female, zm_010 = male)
  voice: "zf_001"
  # Where to store temporary audio files
  temp_folder: "temp_audio"
  # Sample rate for audio generation
  sample_rate: 24000
  # Enable/disable monologue speech
  enabled: true

# Other configuration below can be added as needed